-- Up Migration
-- T-040 (blueprint 7.1, D-078): the countries a member can register with.
--
-- Registration requires a country (`user_account.country_id`), and the form
-- offers the rows of `country`. No migration wrote one, and the seed is
-- refused in production, so a freshly deployed platform offered an empty list
-- and nobody could register at all. The first production deploy found it on
-- 2026-09-25, at the first attempt to create the first account.
--
-- These are FIFA's 211 member associations, keyed by the FIFA trigram as
-- every `country` row is: the football country a member identifies with,
-- which is why England, Scotland, Wales and Northern Ireland are four rows
-- with no ISO code, and why Kosovo has none either (XK is not in ISO 3166).
-- Where a member watches from is a separate question with its own ISO list
-- (`territory`, T-312), never read from this one.
--
-- The nine rows the development seed also writes keep the seed's ids, so the
-- seed's `ON CONFLICT (id)` still finds them. Every other id is new. A row
-- that already exists by code or ISO code -- written by the seed or by
-- `catalog.mjs --add-country` -- is left exactly as it is.
INSERT INTO country (id, code, iso2, name)
SELECT coalesce(v.id, gen_random_uuid()), v.code, v.iso2, v.name
FROM (VALUES
  (NULL::uuid, 'AFG', 'AF'::text, 'Afghanistan'),
  (NULL, 'ALB', 'AL', 'Albania'),
  (NULL, 'ALG', 'DZ', 'Algeria'),
  (NULL, 'ASA', 'AS', 'American Samoa'),
  (NULL, 'AND', 'AD', 'Andorra'),
  (NULL, 'ANG', 'AO', 'Angola'),
  (NULL, 'AIA', 'AI', 'Anguilla'),
  (NULL, 'ATG', 'AG', 'Antigua and Barbuda'),
  (NULL, 'ARG', 'AR', 'Argentina'),
  (NULL, 'ARM', 'AM', 'Armenia'),
  (NULL, 'ARU', 'AW', 'Aruba'),
  (NULL, 'AUS', 'AU', 'Australia'),
  (NULL, 'AUT', 'AT', 'Austria'),
  (NULL, 'AZE', 'AZ', 'Azerbaijan'),
  (NULL, 'BAH', 'BS', 'Bahamas'),
  (NULL, 'BHR', 'BH', 'Bahrain'),
  (NULL, 'BAN', 'BD', 'Bangladesh'),
  (NULL, 'BRB', 'BB', 'Barbados'),
  (NULL, 'BLR', 'BY', 'Belarus'),
  (NULL, 'BEL', 'BE', 'Belgium'),
  (NULL, 'BLZ', 'BZ', 'Belize'),
  (NULL, 'BEN', 'BJ', 'Benin'),
  (NULL, 'BER', 'BM', 'Bermuda'),
  (NULL, 'BHU', 'BT', 'Bhutan'),
  (NULL, 'BOL', 'BO', 'Bolivia'),
  (NULL, 'BIH', 'BA', 'Bosnia and Herzegovina'),
  (NULL, 'BOT', 'BW', 'Botswana'),
  (NULL, 'BRA', 'BR', 'Brazil'),
  (NULL, 'VGB', 'VG', 'British Virgin Islands'),
  (NULL, 'BRU', 'BN', 'Brunei'),
  (NULL, 'BUL', 'BG', 'Bulgaria'),
  (NULL, 'BFA', 'BF', 'Burkina Faso'),
  (NULL, 'BDI', 'BI', 'Burundi'),
  (NULL, 'CAM', 'KH', 'Cambodia'),
  (NULL, 'CMR', 'CM', 'Cameroon'),
  (NULL, 'CAN', 'CA', 'Canada'),
  (NULL, 'CPV', 'CV', 'Cape Verde'),
  (NULL, 'CAY', 'KY', 'Cayman Islands'),
  (NULL, 'CTA', 'CF', 'Central African Republic'),
  (NULL, 'CHA', 'TD', 'Chad'),
  (NULL, 'CHI', 'CL', 'Chile'),
  (NULL, 'CHN', 'CN', 'China'),
  (NULL, 'TPE', 'TW', 'Chinese Taipei'),
  (NULL, 'COL', 'CO', 'Colombia'),
  (NULL, 'COM', 'KM', 'Comoros'),
  (NULL, 'CGO', 'CG', 'Congo'),
  (NULL, 'COK', 'CK', 'Cook Islands'),
  (NULL, 'CRC', 'CR', 'Costa Rica'),
  (NULL, 'CIV', 'CI', 'Côte d''Ivoire'),
  (NULL, 'CRO', 'HR', 'Croatia'),
  (NULL, 'CUB', 'CU', 'Cuba'),
  (NULL, 'CUW', 'CW', 'Curaçao'),
  (NULL, 'CYP', 'CY', 'Cyprus'),
  (NULL, 'CZE', 'CZ', 'Czechia'),
  (NULL, 'DEN', 'DK', 'Denmark'),
  (NULL, 'DJI', 'DJ', 'Djibouti'),
  (NULL, 'DMA', 'DM', 'Dominica'),
  (NULL, 'DOM', 'DO', 'Dominican Republic'),
  (NULL, 'COD', 'CD', 'DR Congo'),
  (NULL, 'ECU', 'EC', 'Ecuador'),
  ('00000000-0000-4000-8000-000000000108', 'EGY', 'EG', 'Egypt'),
  (NULL, 'SLV', 'SV', 'El Salvador'),
  ('00000000-0000-4000-8000-000000000101', 'ENG', NULL, 'England'),
  (NULL, 'EQG', 'GQ', 'Equatorial Guinea'),
  (NULL, 'ERI', 'ER', 'Eritrea'),
  (NULL, 'EST', 'EE', 'Estonia'),
  (NULL, 'SWZ', 'SZ', 'Eswatini'),
  (NULL, 'ETH', 'ET', 'Ethiopia'),
  (NULL, 'FRO', 'FO', 'Faroe Islands'),
  (NULL, 'FIJ', 'FJ', 'Fiji'),
  (NULL, 'FIN', 'FI', 'Finland'),
  ('00000000-0000-4000-8000-000000000105', 'FRA', 'FR', 'France'),
  (NULL, 'GAB', 'GA', 'Gabon'),
  (NULL, 'GAM', 'GM', 'Gambia'),
  (NULL, 'GEO', 'GE', 'Georgia'),
  ('00000000-0000-4000-8000-000000000103', 'GER', 'DE', 'Germany'),
  (NULL, 'GHA', 'GH', 'Ghana'),
  (NULL, 'GIB', 'GI', 'Gibraltar'),
  (NULL, 'GRE', 'GR', 'Greece'),
  (NULL, 'GRN', 'GD', 'Grenada'),
  (NULL, 'GUM', 'GU', 'Guam'),
  (NULL, 'GUA', 'GT', 'Guatemala'),
  (NULL, 'GUI', 'GN', 'Guinea'),
  (NULL, 'GNB', 'GW', 'Guinea-Bissau'),
  (NULL, 'GUY', 'GY', 'Guyana'),
  (NULL, 'HAI', 'HT', 'Haiti'),
  (NULL, 'HON', 'HN', 'Honduras'),
  (NULL, 'HKG', 'HK', 'Hong Kong'),
  (NULL, 'HUN', 'HU', 'Hungary'),
  (NULL, 'ISL', 'IS', 'Iceland'),
  (NULL, 'IND', 'IN', 'India'),
  (NULL, 'IDN', 'ID', 'Indonesia'),
  ('00000000-0000-4000-8000-000000000109', 'IRN', 'IR', 'Iran'),
  (NULL, 'IRQ', 'IQ', 'Iraq'),
  (NULL, 'IRL', 'IE', 'Ireland'),
  (NULL, 'ISR', 'IL', 'Israel'),
  ('00000000-0000-4000-8000-000000000104', 'ITA', 'IT', 'Italy'),
  (NULL, 'JAM', 'JM', 'Jamaica'),
  (NULL, 'JPN', 'JP', 'Japan'),
  (NULL, 'JOR', 'JO', 'Jordan'),
  (NULL, 'KAZ', 'KZ', 'Kazakhstan'),
  (NULL, 'KEN', 'KE', 'Kenya'),
  (NULL, 'KVX', NULL, 'Kosovo'),
  (NULL, 'KUW', 'KW', 'Kuwait'),
  (NULL, 'KGZ', 'KG', 'Kyrgyzstan'),
  (NULL, 'LAO', 'LA', 'Laos'),
  (NULL, 'LVA', 'LV', 'Latvia'),
  (NULL, 'LBN', 'LB', 'Lebanon'),
  (NULL, 'LES', 'LS', 'Lesotho'),
  (NULL, 'LBR', 'LR', 'Liberia'),
  (NULL, 'LBY', 'LY', 'Libya'),
  (NULL, 'LIE', 'LI', 'Liechtenstein'),
  (NULL, 'LTU', 'LT', 'Lithuania'),
  (NULL, 'LUX', 'LU', 'Luxembourg'),
  (NULL, 'MAC', 'MO', 'Macau'),
  (NULL, 'MAD', 'MG', 'Madagascar'),
  (NULL, 'MWI', 'MW', 'Malawi'),
  (NULL, 'MAS', 'MY', 'Malaysia'),
  (NULL, 'MDV', 'MV', 'Maldives'),
  (NULL, 'MLI', 'ML', 'Mali'),
  (NULL, 'MLT', 'MT', 'Malta'),
  (NULL, 'MTN', 'MR', 'Mauritania'),
  (NULL, 'MRI', 'MU', 'Mauritius'),
  (NULL, 'MEX', 'MX', 'Mexico'),
  (NULL, 'MDA', 'MD', 'Moldova'),
  (NULL, 'MNG', 'MN', 'Mongolia'),
  (NULL, 'MNE', 'ME', 'Montenegro'),
  (NULL, 'MSR', 'MS', 'Montserrat'),
  (NULL, 'MAR', 'MA', 'Morocco'),
  (NULL, 'MOZ', 'MZ', 'Mozambique'),
  (NULL, 'MYA', 'MM', 'Myanmar'),
  (NULL, 'NAM', 'NA', 'Namibia'),
  (NULL, 'NEP', 'NP', 'Nepal'),
  ('00000000-0000-4000-8000-000000000107', 'NED', 'NL', 'Netherlands'),
  (NULL, 'NCL', 'NC', 'New Caledonia'),
  (NULL, 'NZL', 'NZ', 'New Zealand'),
  (NULL, 'NCA', 'NI', 'Nicaragua'),
  (NULL, 'NIG', 'NE', 'Niger'),
  (NULL, 'NGA', 'NG', 'Nigeria'),
  (NULL, 'PRK', 'KP', 'North Korea'),
  (NULL, 'MKD', 'MK', 'North Macedonia'),
  (NULL, 'NIR', NULL, 'Northern Ireland'),
  (NULL, 'NOR', 'NO', 'Norway'),
  (NULL, 'OMA', 'OM', 'Oman'),
  (NULL, 'PAK', 'PK', 'Pakistan'),
  (NULL, 'PLE', 'PS', 'Palestine'),
  (NULL, 'PAN', 'PA', 'Panama'),
  (NULL, 'PNG', 'PG', 'Papua New Guinea'),
  (NULL, 'PAR', 'PY', 'Paraguay'),
  (NULL, 'PER', 'PE', 'Peru'),
  (NULL, 'PHI', 'PH', 'Philippines'),
  (NULL, 'POL', 'PL', 'Poland'),
  ('00000000-0000-4000-8000-000000000106', 'POR', 'PT', 'Portugal'),
  (NULL, 'PUR', 'PR', 'Puerto Rico'),
  (NULL, 'QAT', 'QA', 'Qatar'),
  (NULL, 'ROU', 'RO', 'Romania'),
  (NULL, 'RUS', 'RU', 'Russia'),
  (NULL, 'RWA', 'RW', 'Rwanda'),
  (NULL, 'SKN', 'KN', 'Saint Kitts and Nevis'),
  (NULL, 'LCA', 'LC', 'Saint Lucia'),
  (NULL, 'VIN', 'VC', 'Saint Vincent and the Grenadines'),
  (NULL, 'SAM', 'WS', 'Samoa'),
  (NULL, 'SMR', 'SM', 'San Marino'),
  (NULL, 'STP', 'ST', 'São Tomé and Príncipe'),
  (NULL, 'KSA', 'SA', 'Saudi Arabia'),
  (NULL, 'SCO', NULL, 'Scotland'),
  (NULL, 'SEN', 'SN', 'Senegal'),
  (NULL, 'SRB', 'RS', 'Serbia'),
  (NULL, 'SEY', 'SC', 'Seychelles'),
  (NULL, 'SLE', 'SL', 'Sierra Leone'),
  (NULL, 'SIN', 'SG', 'Singapore'),
  (NULL, 'SVK', 'SK', 'Slovakia'),
  (NULL, 'SVN', 'SI', 'Slovenia'),
  (NULL, 'SOL', 'SB', 'Solomon Islands'),
  (NULL, 'SOM', 'SO', 'Somalia'),
  (NULL, 'RSA', 'ZA', 'South Africa'),
  (NULL, 'KOR', 'KR', 'South Korea'),
  (NULL, 'SSD', 'SS', 'South Sudan'),
  ('00000000-0000-4000-8000-000000000102', 'ESP', 'ES', 'Spain'),
  (NULL, 'SRI', 'LK', 'Sri Lanka'),
  (NULL, 'SDN', 'SD', 'Sudan'),
  (NULL, 'SUR', 'SR', 'Suriname'),
  (NULL, 'SWE', 'SE', 'Sweden'),
  (NULL, 'SUI', 'CH', 'Switzerland'),
  (NULL, 'SYR', 'SY', 'Syria'),
  (NULL, 'TAH', 'PF', 'Tahiti'),
  (NULL, 'TJK', 'TJ', 'Tajikistan'),
  (NULL, 'TAN', 'TZ', 'Tanzania'),
  (NULL, 'THA', 'TH', 'Thailand'),
  (NULL, 'TLS', 'TL', 'Timor-Leste'),
  (NULL, 'TOG', 'TG', 'Togo'),
  (NULL, 'TGA', 'TO', 'Tonga'),
  (NULL, 'TRI', 'TT', 'Trinidad and Tobago'),
  (NULL, 'TUN', 'TN', 'Tunisia'),
  (NULL, 'TUR', 'TR', 'Türkiye'),
  (NULL, 'TKM', 'TM', 'Turkmenistan'),
  (NULL, 'TCA', 'TC', 'Turks and Caicos Islands'),
  (NULL, 'UGA', 'UG', 'Uganda'),
  (NULL, 'UKR', 'UA', 'Ukraine'),
  (NULL, 'UAE', 'AE', 'United Arab Emirates'),
  (NULL, 'USA', 'US', 'United States'),
  (NULL, 'VIR', 'VI', 'United States Virgin Islands'),
  (NULL, 'URU', 'UY', 'Uruguay'),
  (NULL, 'UZB', 'UZ', 'Uzbekistan'),
  (NULL, 'VAN', 'VU', 'Vanuatu'),
  (NULL, 'VEN', 'VE', 'Venezuela'),
  (NULL, 'VIE', 'VN', 'Vietnam'),
  (NULL, 'WAL', NULL, 'Wales'),
  (NULL, 'YEM', 'YE', 'Yemen'),
  (NULL, 'ZAM', 'ZM', 'Zambia'),
  (NULL, 'ZIM', 'ZW', 'Zimbabwe')
) AS v (id, code, iso2, name)
ON CONFLICT DO NOTHING;

-- Down Migration

-- A country a member registered with, or a competition, team, venue or
-- person points at, cannot go (every reference is ON DELETE RESTRICT) and is
-- kept; the rest of these codes are removed, whoever wrote them.
DO $$
DECLARE
  target uuid;
BEGIN
  FOR target IN
    SELECT id FROM country WHERE code = ANY (ARRAY[
      'AFG', 'ALB', 'ALG', 'ASA', 'AND', 'ANG', 'AIA', 'ATG', 'ARG', 'ARM', 'ARU', 'AUS',
      'AUT', 'AZE', 'BAH', 'BHR', 'BAN', 'BRB', 'BLR', 'BEL', 'BLZ', 'BEN', 'BER', 'BHU',
      'BOL', 'BIH', 'BOT', 'BRA', 'VGB', 'BRU', 'BUL', 'BFA', 'BDI', 'CAM', 'CMR', 'CAN',
      'CPV', 'CAY', 'CTA', 'CHA', 'CHI', 'CHN', 'TPE', 'COL', 'COM', 'CGO', 'COK', 'CRC',
      'CIV', 'CRO', 'CUB', 'CUW', 'CYP', 'CZE', 'DEN', 'DJI', 'DMA', 'DOM', 'COD', 'ECU',
      'EGY', 'SLV', 'ENG', 'EQG', 'ERI', 'EST', 'SWZ', 'ETH', 'FRO', 'FIJ', 'FIN', 'FRA',
      'GAB', 'GAM', 'GEO', 'GER', 'GHA', 'GIB', 'GRE', 'GRN', 'GUM', 'GUA', 'GUI', 'GNB',
      'GUY', 'HAI', 'HON', 'HKG', 'HUN', 'ISL', 'IND', 'IDN', 'IRN', 'IRQ', 'IRL', 'ISR',
      'ITA', 'JAM', 'JPN', 'JOR', 'KAZ', 'KEN', 'KVX', 'KUW', 'KGZ', 'LAO', 'LVA', 'LBN',
      'LES', 'LBR', 'LBY', 'LIE', 'LTU', 'LUX', 'MAC', 'MAD', 'MWI', 'MAS', 'MDV', 'MLI',
      'MLT', 'MTN', 'MRI', 'MEX', 'MDA', 'MNG', 'MNE', 'MSR', 'MAR', 'MOZ', 'MYA', 'NAM',
      'NEP', 'NED', 'NCL', 'NZL', 'NCA', 'NIG', 'NGA', 'PRK', 'MKD', 'NIR', 'NOR', 'OMA',
      'PAK', 'PLE', 'PAN', 'PNG', 'PAR', 'PER', 'PHI', 'POL', 'POR', 'PUR', 'QAT', 'ROU',
      'RUS', 'RWA', 'SKN', 'LCA', 'VIN', 'SAM', 'SMR', 'STP', 'KSA', 'SCO', 'SEN', 'SRB',
      'SEY', 'SLE', 'SIN', 'SVK', 'SVN', 'SOL', 'SOM', 'RSA', 'KOR', 'SSD', 'ESP', 'SRI',
      'SDN', 'SUR', 'SWE', 'SUI', 'SYR', 'TAH', 'TJK', 'TAN', 'THA', 'TLS', 'TOG', 'TGA',
      'TRI', 'TUN', 'TUR', 'TKM', 'TCA', 'UGA', 'UKR', 'UAE', 'USA', 'VIR', 'URU', 'UZB',
      'VAN', 'VEN', 'VIE', 'WAL', 'YEM', 'ZAM', 'ZIM'
    ])
  LOOP
    BEGIN
      DELETE FROM country WHERE id = target;
    EXCEPTION WHEN restrict_violation OR foreign_key_violation THEN
      NULL;
    END;
  END LOOP;
END $$;
