-- Up Migration
-- T-820: data-quality findings over the stored feed (E82, D-097).
--
-- One row per thing a check found wrong, naming the check and what it is
-- about (a fixture, one side of one, a pair of fixtures, a team in a season's
-- table). Nothing here corrects the data: a finding is a question for a
-- person, never an edit.
--
-- A finding is open while the check keeps finding it (`last_seen_at` moves on
-- every sweep that sees it) and resolved when a sweep no longer does. The
-- partial unique index is what keeps one row per (check, subject) while it is
-- unresolved, so a check that runs every few minutes never writes a second
-- row for the same problem. A problem that comes back after it was resolved
-- is a new row: the old one is history.
--
-- `reviewed_*` is T-821: an administrator marks a finding reviewed with a
-- reason (and an audit row); it stays reviewed until it resolves.
-- Additive: no existing table changes, no backfill.

CREATE TABLE data_quality_finding (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  check_kind         text NOT NULL,
  subject_key        text NOT NULL,
  fixture_id         uuid REFERENCES fixture (id) ON DELETE CASCADE,
  related_fixture_id uuid REFERENCES fixture (id) ON DELETE CASCADE,
  team_id            uuid REFERENCES team (id) ON DELETE CASCADE,
  season_id          uuid REFERENCES season (id) ON DELETE CASCADE,
  competition_id     uuid REFERENCES competition (id) ON DELETE CASCADE,
  detail             text NOT NULL,
  first_seen_at      timestamptz NOT NULL,
  last_seen_at       timestamptz NOT NULL,
  resolved_at        timestamptz,
  reviewed_at        timestamptz,
  reviewed_by        uuid REFERENCES user_account (id) ON DELETE SET NULL,
  review_reason      text,
  CONSTRAINT data_quality_finding_check_kind CHECK (
    check_kind IN (
      'finished_without_score', 'goals_disagree', 'live_overrun',
      'lineup_not_eleven', 'fixture_mapped_twice', 'duplicate_fixture',
      'table_disagrees'
    )
  ),
  CONSTRAINT data_quality_finding_subject_not_blank CHECK (btrim(subject_key) <> ''),
  CONSTRAINT data_quality_finding_detail_not_blank CHECK (btrim(detail) <> ''),
  CONSTRAINT data_quality_finding_seen_ordered CHECK (last_seen_at >= first_seen_at),
  CONSTRAINT data_quality_finding_resolved_after_seen
    CHECK (resolved_at IS NULL OR resolved_at >= last_seen_at),
  CONSTRAINT data_quality_finding_review_has_reason CHECK (
    (reviewed_at IS NULL AND review_reason IS NULL)
    OR (reviewed_at IS NOT NULL AND btrim(review_reason) <> '')
  )
);

CREATE UNIQUE INDEX data_quality_finding_open_once
  ON data_quality_finding (check_kind, subject_key)
  WHERE resolved_at IS NULL;
CREATE INDEX data_quality_finding_open_competition_idx
  ON data_quality_finding (competition_id)
  WHERE resolved_at IS NULL;
CREATE INDEX data_quality_finding_fixture_idx ON data_quality_finding (fixture_id);
CREATE INDEX data_quality_finding_related_fixture_idx ON data_quality_finding (related_fixture_id);
CREATE INDEX data_quality_finding_team_idx ON data_quality_finding (team_id);
CREATE INDEX data_quality_finding_season_idx ON data_quality_finding (season_id);
CREATE INDEX data_quality_finding_reviewed_by_idx ON data_quality_finding (reviewed_by);

COMMENT ON TABLE data_quality_finding IS
  'Data-quality findings over the stored feed (T-820): one row per (check, subject) while unresolved, first and last seen, resolved when a sweep no longer finds it. Never a correction.';
COMMENT ON COLUMN data_quality_finding.subject_key IS
  'What the finding is about, stable across sweeps within one check: a fixture id, a fixture id and side, two fixture ids, or a season and team.';

-- When each check last ran, so that "no findings" can be told apart from "not
-- checked lately" (rule 4): the admin page and the watchdog read it.
CREATE TABLE data_quality_check_run (
  check_kind text PRIMARY KEY,
  checked_at timestamptz NOT NULL,
  CONSTRAINT data_quality_check_run_check_kind CHECK (
    check_kind IN (
      'finished_without_score', 'goals_disagree', 'live_overrun',
      'lineup_not_eleven', 'fixture_mapped_twice', 'duplicate_fixture',
      'table_disagrees'
    )
  )
);

COMMENT ON TABLE data_quality_check_run IS
  'The newest run of each data-quality check (T-820), one row per check, rewritten by every run.';

-- Down Migration

DROP TABLE data_quality_check_run;
DROP TABLE data_quality_finding;
