-- Up Migration
-- T-805 (D-101): the backup and the restore drill say what happened, where the
-- API can read it. Both run on the host from systemd timers
-- (scripts/backup/), not in the API, so until now the watchdog's `backup`
-- condition could only say `unknown`.
--
-- `backup_run` is one row per finished run, written by `backup.sh` and
-- `restore-drill.sh` through `psql` in the postgres container as the last thing
-- they do, pass or fail. The watchdog reads the newest successful backup's age
-- and the newest drill. Append-only in practice (nothing in the API writes it);
-- a few hundred rows a year, so no pruning.
-- Additive: no existing table changes, no backfill.

CREATE TABLE backup_run (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind        text NOT NULL,
  started_at  timestamptz NOT NULL,
  finished_at timestamptz NOT NULL DEFAULT now(),
  ok          boolean NOT NULL,
  -- The dump the run wrote or restored (`fmip-<stamp>.dump`), when there is one.
  subject     text,
  -- Where it came from for a drill (`offsite` | `local`), what failed otherwise.
  detail      text,
  CONSTRAINT backup_run_kind CHECK (kind IN ('backup', 'restore_drill')),
  CONSTRAINT backup_run_order CHECK (started_at <= finished_at),
  CONSTRAINT backup_run_detail_length CHECK (length(detail) <= 2000)
);

CREATE INDEX backup_run_kind_idx ON backup_run (kind, finished_at DESC);

COMMENT ON TABLE backup_run IS
  'One row per finished backup or restore drill (T-805), written by scripts/backup/*.sh via psql. The watchdog reads it for the backup and restore_drill conditions.';

-- Down Migration

DROP TABLE backup_run;
