-- Up Migration
-- T-801: the watchdog over the health views. Two tables:
--
-- `watchdog_condition` is the current state, one row per condition, rewritten
-- by every tick: its level, since when, what was measured and against which
-- threshold. Small (a dozen rows), and the only mutable half.
--
-- `watchdog_event` is the log of transitions, append-only: a row is written
-- only when a condition's level changes, so a condition that stays bad for an
-- hour is one `raised` row and one `recovered` row, never sixty. The alerts
-- (T-802) are the `raised` and `recovered` rows, read by id after a cursor.
-- Additive: no existing table changes, no backfill.

CREATE TABLE watchdog_event (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  condition   text NOT NULL,
  at          timestamptz NOT NULL,
  from_level  text NOT NULL,
  to_level    text NOT NULL,
  kind        text NOT NULL,
  incident_id bigint REFERENCES watchdog_event (id),
  observed    double precision,
  note        text,
  CONSTRAINT watchdog_event_levels
    CHECK (from_level IN ('ok', 'degraded', 'failing', 'unknown')
       AND to_level IN ('ok', 'degraded', 'failing', 'unknown')
       AND from_level <> to_level),
  CONSTRAINT watchdog_event_kind
    CHECK (kind IN ('raised', 'escalated', 'eased', 'recovered', 'unobservable', 'observable')),
  -- A raised event opens its own incident (the id is drawn before the insert,
  -- so the row names itself); every other kind inside an incident names the
  -- raised one.
  CONSTRAINT watchdog_event_raised_is_own_incident
    CHECK (kind <> 'raised' OR incident_id = id)
);

CREATE INDEX watchdog_event_condition_idx ON watchdog_event (condition, id DESC);

COMMENT ON TABLE watchdog_event IS
  'Watchdog transitions (T-801): one row per change of a condition''s level, never one per tick. raised and recovered are the alerts (T-802). Append-only.';
COMMENT ON COLUMN watchdog_event.incident_id IS
  'The raised event that opened the incident this event belongs to; its own id for a raised event; NULL outside an incident.';

CREATE TRIGGER watchdog_event_immutable
  BEFORE UPDATE OR DELETE ON watchdog_event FOR EACH ROW EXECUTE FUNCTION refuse_change();

CREATE TABLE watchdog_condition (
  key            text PRIMARY KEY,
  level          text NOT NULL,
  since          timestamptz NOT NULL,
  checked_at     timestamptz NOT NULL,
  observed       double precision,
  unit           text NOT NULL,
  degraded_at    double precision NOT NULL,
  failing_at     double precision NOT NULL,
  note           text,
  incident_id    bigint REFERENCES watchdog_event (id),
  CONSTRAINT watchdog_condition_key CHECK (key ~ '^[a-z_]+(:[a-z0-9_-]+)?$'),
  CONSTRAINT watchdog_condition_level CHECK (level IN ('ok', 'degraded', 'failing', 'unknown')),
  CONSTRAINT watchdog_condition_unit CHECK (unit IN ('seconds', 'percent', 'count')),
  CONSTRAINT watchdog_condition_since_before_check CHECK (since <= checked_at),
  -- An open incident is never ok: recovering closes it.
  CONSTRAINT watchdog_condition_ok_has_no_incident CHECK (level <> 'ok' OR incident_id IS NULL)
);

COMMENT ON TABLE watchdog_condition IS
  'The watchdog''s current state per condition (T-801): level, since, the measured value, the thresholds, the open incident. Rewritten every tick; transitions go to watchdog_event.';

-- Down Migration

DROP TABLE watchdog_condition;
DROP TABLE watchdog_event;
