-- Up Migration
-- T-913: asking the feed again for one fixture's details (E91, D-110).
--
-- An administrator queues a fixture, or every fixture behind one check's open
-- findings in one season, with a reason (audited in `audit_log`). The
-- post-match job carries the queue within its own share of the day's request
-- budget: it asks the provider for the fixture's details through the same
-- writer as any other detail, and records when it asked and whether the answer
-- changed anything we store. Nothing here corrects a value by hand: the
-- finding resolves on the next sweep if the new answer agrees, and stays open
-- if it does not ("asked again on <date>, unchanged").
--
-- One pending request per fixture (the partial unique index). A request the
-- job has carried is history, and a later request for the same fixture is a
-- new row. Additive: no existing table changes, no backfill.

CREATE TABLE fixture_refetch_request (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fixture_id   uuid NOT NULL REFERENCES fixture (id) ON DELETE CASCADE,
  requested_by uuid REFERENCES user_account (id) ON DELETE SET NULL,
  requested_at timestamptz NOT NULL DEFAULT now(),
  reason       text NOT NULL,
  -- The class it was queued for, when it was queued with one.
  check_kind   text,
  season_id    uuid REFERENCES season (id) ON DELETE CASCADE,
  -- Set when the job asked the provider and wrote the answer.
  fetched_at   timestamptz,
  -- Whether that answer changed any stored row of the fixture.
  changed      boolean,
  CONSTRAINT fixture_refetch_request_reason_not_blank CHECK (btrim(reason) <> ''),
  CONSTRAINT fixture_refetch_request_check_kind CHECK (
    check_kind IS NULL OR check_kind IN (
      'finished_without_score', 'goals_disagree', 'live_overrun',
      'lineup_not_eleven', 'fixture_mapped_twice', 'duplicate_fixture',
      'table_disagrees'
    )
  ),
  CONSTRAINT fixture_refetch_request_outcome_complete
    CHECK ((fetched_at IS NULL) = (changed IS NULL)),
  CONSTRAINT fixture_refetch_request_fetched_after_request
    CHECK (fetched_at IS NULL OR fetched_at >= requested_at)
);

CREATE UNIQUE INDEX fixture_refetch_request_pending_once
  ON fixture_refetch_request (fixture_id)
  WHERE fetched_at IS NULL;
CREATE INDEX fixture_refetch_request_pending_idx
  ON fixture_refetch_request (requested_at)
  WHERE fetched_at IS NULL;
CREATE INDEX fixture_refetch_request_fetched_idx
  ON fixture_refetch_request (fetched_at)
  WHERE fetched_at IS NOT NULL;
CREATE INDEX fixture_refetch_request_fixture_idx ON fixture_refetch_request (fixture_id);
CREATE INDEX fixture_refetch_request_requested_by_idx ON fixture_refetch_request (requested_by);
CREATE INDEX fixture_refetch_request_season_idx ON fixture_refetch_request (season_id);

COMMENT ON TABLE fixture_refetch_request IS
  'A fixture whose details an administrator asked the feed for again (T-913, D-110): the reason, when the post-match job asked, and whether the answer changed anything. Never a correction by hand.';

-- Down Migration

DROP TABLE fixture_refetch_request;
